export const orders = [
	{
		fecha: '1/10/2022',
		hora: '8:00',
		estado: 'guardado',
		largo: '1',
		ancho: '5',
		alto: '3',
		peso: '3.5',
		direccionRecogida: 'Calle 7 5 25',
		ciudadRecogida: 'Cali',
		nombreDestinatario: 'Pedro Gomez',
		cedulaNitDestinatario: '6400230',
		direccionEntrega: 'Avenida Cali',
		ciudadEntrega: 'Bogota',
	},
	{
		fecha: '2/10/2022',
		hora: '8:30',
		estado: 'pendiente',
		largo: '2',
		ancho: '3',
		alto: '2',
		peso: '2.5',
		direccionRecogida: 'Carrera 4 6 23',
		ciudadRecogida: 'Palmira',
		nombreDestinatario: 'Jose Ramirez',
		cedulaNitDestinatario: '94200325',
		direccionEntrega: 'Calle 9 7 46',
		ciudadEntrega: 'Barranquilla',
	},
	{
		fecha: '3/10/2022',
		hora: '9:00',
		estado: 'bodega',
		largo: '3',
		ancho: '5',
		alto: '3',
		peso: '1.5',
		direccionRecogida: 'Avenida 5 No 2 4 3',
		ciudadRecogida: 'Buga',
		nombreDestinatario: 'Luis Castillo',
		cedulaNitDestinatario: '91525789',
		direccionEntrega: 'Carrera 25 13 78',
		ciudadEntrega: 'Valledupar',
	},
	{
		fecha: '4/10/2022',
		hora: '9:30',
		estado: 'pendiente',
		largo: '4',
		ancho: '4',
		alto: '4',
		peso: '4',
		direccionRecogida: 'Carrera 6 8 22',
		ciudadRecogida: 'Tulua',
		nombreDestinatario: 'Ramiro Reyes',
		cedulaNitDestinatario: '6045280',
		direccionEntrega: 'Calle 45 12 66',
		ciudadEntrega: 'Cali',
	},
	{
		fecha: '5/10/2022',
		hora: '14:00',
		estado: 'pendiente',
		largo: '5',
		ancho: '3',
		alto: '9',
		peso: '6',
		direccionRecogida: 'Transv 7 Diag 4 89',
		ciudadRecogida: 'Palmira',
		nombreDestinatario: 'Lisandro Soto',
		cedulaNitDestinatario: '6398478',
		direccionEntrega: 'Avenida del Rio',
		ciudadEntrega: 'Medellin',
	},
	{
		fecha: '6/10/2022',
		hora: '14:15',
		estado: 'guardado',
		largo: '6',
		ancho: '5',
		alto: '7',
		peso: '5.45',
		direccionRecogida: 'Calle 15 3 65',
		ciudadRecogida: 'Buenaventura',
		nombreDestinatario: 'Carlos Buendia',
		cedulaNitDestinatario: '1112225456',
		direccionEntrega: 'Fontibon Cra 25 4 60',
		ciudadEntrega: 'Bogota',
	},
	{
		fecha: '7/10/2022',
		hora: '14:19',
		estado: 'guardado',
		largo: '7',
		ancho: '4',
		alto: '8',
		peso: '6.1',
		direccionRecogida: 'Calle 7 5 26',
		ciudadRecogida: 'Cali',
		nombreDestinatario: 'Gerardo Caicedo',
		cedulaNitDestinatario: '1111221789',
		direccionEntrega: 'Avenida principal',
		ciudadEntrega: 'Sogamoso',
	},
	{
		fecha: '8/10/2022',
		hora: '14:25',
		estado: 'guardado',
		largo: '8',
		ancho: '2',
		alto: '10',
		peso: '6.75',
		direccionRecogida: 'Carrera 4 6 24',
		ciudadRecogida: 'Cali',
		nombreDestinatario: 'Miguel Lopez',
		cedulaNitDestinatario: '1001789256',
		direccionEntrega: 'Carrera 90 12 07',
		ciudadEntrega: 'Duitama',
	},
	{
		fecha: '9/10/2022',
		hora: '13:01',
		estado: 'bodega',
		largo: '9',
		ancho: '9',
		alto: '9',
		peso: '7.4',
		direccionRecogida: 'Avenida 5 No 2 4 4',
		ciudadRecogida: 'Palmira',
		nombreDestinatario: 'Maria Dominguez',
		cedulaNitDestinatario: '1112223000',
		direccionEntrega: 'Calle 8 18 65',
		ciudadEntrega: 'La Dorada',
	},
	{
		fecha: '10/10/2022',
		hora: '13:16',
		estado: 'bodega',
		largo: '10',
		ancho: '8',
		alto: '3',
		peso: '8.05',
		direccionRecogida: 'Carrera 6 8 23',
		ciudadRecogida: 'Buga',
		nombreDestinatario: 'Ana Solarte',
		cedulaNitDestinatario: '29700831',
		direccionEntrega: 'Edificio El llanero',
		ciudadEntrega: 'Villavicencio',
	},
]
